# action.yml
name: 'Content Label'
description: 'Generator'
inputs:
  count-forked:  # id of input
    description: 'Include forked repos'
    required: true
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.count-forked }}
